[package]
name = "linlogalg"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "linlogalg"
path = "src/main.rs"

[dependencies]
logic2geometry = {path="../lib/logic2geometry"}
mll = { path="../lib/mll"}
proof_net = { path="../lib/proof_net/"}
algebra = {path="../lib/algebra"}
